pytest-dev/pytest-html

- pytest_html/plugin.py
This fixes a `DeprecationWarning`:
```
[...]
File "/home/buildbotx/slaves/slave/ubuntu-utopic/build/.tox/unittests/lib/python3.4/site-packages/pytest_html/plugin.py", line 115, in _appendrow
log.append(raw(cgi.escape(line)))
File "/usr/lib/python3.4/cgi.py", line 1039, in escape
DeprecationWarning, stacklevel=2)
[...]
Message: '%s'
Arguments: ('/home/buildbotx/slaves/slave/ubuntu-utopic/build/.tox/unittests/lib/python3.4/site-packages/pytest_html/plugin.py:115: DeprecationWarning: cgi.escape is deprecated, use html.escape instead\n  log.append(raw(cgi.escape(line)))\n',)
```
> Use html.escape instead of cgi.escape on Python 3.

- pytest_html/plugin.py
- pytest_html/resources/main.js
This sorts tests by the results column by default, and defines a custom sorting which shows the tests roughly in order of importance so failed/skipped tests stand out from (hopefully many) passed ones.
Note I didn't write much javascript before that, so a thorough review is appreciated - it seems to work fine for me though.
A new release after this would be appreciated :wink:
> Improve sorting

- README.rst
- pytest_html/newhooks.py
- pytest_html/plugin.py
- test_pytest_html.py
@The-Compiler would you mind taking a look at this? It allows me to include duplicate row headers by avoiding dictionaries. It also removed the uneccessary custom hook.
> Replace custom hook with fixture for setting environment section

- pytest_html/plugin.py
- test_pytest_html.py
> Fix INTERNALERROR when an xdist slave crashes.

- .gitignore
As described in #55, the necessary files have been included in .gitignore :
* Pycharm IDE - Jetbrains.
* PyDev IDE - Eclipse.
* YouCompleteMe plugin - VIM.
> Include IDE specific files in gitignore.

- pytest_html/plugin.py
This PR exercises a minor refactor in `HTMLReport` class. The performance of plugin remains unaltered. 
* `pytest_sessionfinish` method used to open the logfile, write all the html content, and finally close and save it.
* This method has been split to two separate methods: `_generate_report` and `_save_report`.
* `_generate_report` returns a unicode string with all the content.
* `_save_report` accepts this as a param and writes it to the logfile.
* `pytest_sessionfinish` calls both of these methods one after another.
> Split pytest_sessionfinish into generate and save methods.

- pytest_html/resources/main.js
Clean up table before calling appendElement for each element.
Actually table is completely removed and created a new one. This is the
fastest way to have clean table.
This approach is ~10% faster in chromium and ~400% faster in Firefox.
Here is sample report pages:
With this patch: https://r-ci.tk/stuff/pytest.html
Without this patch: https://r-ci.tk/stuff/pytest-old.html
Closes #59
> Optimize results sorting

- pytest_html/extras.py
- pytest_html/plugin.py
- testing/test_pytest_html.py
It would be nice if the report support JPEG and SVG images. At the moment it only supports PNG. And if the image is not a png the browser can't display the image properly.
> Add support for jpg and svg

- pytest_html/plugin.py
- testing/test_pytest_html.py
> Always encode content for data URI

- .travis.yml
- README.rst
- tox.ini
Only run tests against the latest versions of all dependencies.
> Use latest dependencies when running tests

- pytest_html/plugin.py
- testing/test_pytest_html.py
Replaces and closes #119 without pytest 2.9 workaround.
> Fixed handling unicode longrepr values. Fixes #114.

- setup.py
Since #121 pytest < 3 is no longer supported
Related to #122
> Require pytest >= 3.0 to install

- pytest_html/plugin.py
- testing/test_pytest_html.py
I got decoding issue when create extra "text".  Extra "text" contains em-dash "—" as bytes "\xe2\x80\x94".
> INTERNALERROR> Traceback (most recent call last):
> INTERNALERROR>   File "C:\Python27\lib\site-packages\_pytest\main.py", line 98, in wrap_session
> INTERNALERROR>     session.exitstatus = doit(config, session) or 0
> INTERNALERROR>   File "C:\Python27\lib\site-packages\_pytest\main.py", line 133, in _main
> INTERNALERROR>     config.hook.pytest_runtestloop(session=session)
> INTERNALERROR>   File "C:\Python27\lib\site-packages\_pytest\vendored_packages\pluggy.py", line 745, in __call__
> INTERNALERROR>     return self._hookexec(self, self._nonwrappers + self._wrappers, kwargs)
> INTERNALERROR>   File "C:\Python27\lib\site-packages\_pytest\vendored_packages\pluggy.py", line 339, …
> Always decode byte in 'extra text' and change ordering according to latest pytest-rerunfailures

- pytest_html/plugin.py
- testing/test_pytest_html.py
I wanted to show a lists of file names in the metadata view but they were concatenated together in one long string. I think it would be more useful if list like types are rendered as strings with comma seperators.
> Fix render metadata list value

- pytest_html/plugin.py
- pytest_html/resources/style.css
- testing/test_pytest_html.py
We have a CI dashboard with links to the reports generated for different tests. I'd like to see the filename of the report as title in the body, so it's clear which test results I'm looking at.
Note: I made the assumption that `os.path.basename` will work across platforms.
> adds filename of report as title to html body

- README.rst
- pytest_html/hooks.py
- pytest_html/plugin.py
- pytest_html/resources/style.css
- testing/test_pytest_html.py
resolves #109 by implementing pytest_html_results_summary hook
Hook allows adding data in a table in the Summary section. Styling is same as table in Environment section.
> Additional content in summary section

- README.rst
- pytest_html/resources/main.js
- testing/test.js
Closes #157 
The query param code is based on https://stackoverflow.com/a/5158301/429533.
> Customize collapsed rows with a query param

- pytest_html/__init__.py
In frozen executables created with tools such as pyinstaller, get_distribution() does not work because it looks for files in the environment which are not packed in the
executable.
This patch makes `__version__` available in those situations, otherwise the
plugin won't work at all because `plugin.py` tries to import `__version__`
from `pytest_html.__init__`.
> Always define __version__ even if get_distribution() fails

- pytest_html/plugin.py
Change the default value for `--css` option to an empty array instead of None since the config reading code is doing that manually.
> Refactor css config code

- pytest_html/plugin.py
- testing/test_pytest_html.py
A little context:
I've been using pytest_html for layouts testing, sometimes reports contains about 100 mb of images, which is hard to navigate in browser. It would be nice if I could just scroll throw my assets and watch which test-case was failed in my file manager. 
I found out that assets naming contains exact info I need, but in some reason it hashed. 
So I added an option assets_name_hashing. When it's set False, assets names are not hashed and can be sorted nicely in folder. 
What do you think? 
Update: 
now all assets named like "test_name_[hash].jpg"
> Change assets naming method

- .gitignore
- pytest_html/plugin.py
- testing/test_pytest_html.py
When the --html flag is used in pytest.ini with "addopts" and the
report title is stored in an environment variable, the name of the
environment variable was used as the report title.
In other words, the environment variable was never expanded.
Fixes: #201
> Handle when report title is stored as an environment variable

- pytest_html/plugin.py
By default terminals would open files in editors and URLs in browsers.
By printing the generated html report using an URL (file://) we enable
users to click the terminal to open it. Previously this opened the file
in the text editor which is very unlikely to be what user would want.
> Allow opening generated html report in browser

- pytest_html/plugin.py
- testing/test_pytest_html.py
When a test name is long (that might include class hierarchy and parametrization), the generated filename may exceed max supported length.
This PR truncates long names to avoid that, while preserving hashes of non-truncated names.
> Truncate long test names in assets.

- pytest_html/plugin.py
The content in log sections doesn't always include a trailing newline, so this includes one afterwards ensuring that the next section header is placed on a new line.
This is only really useful if there are multiple log sections, like in the example below. If there's already a trailing newline, this has no effect as it adds a `<br>` tag which doesn't change the spacing at the end of the content.
<details>
<summary>Example</summary>
```python
import pytest
@pytest.fixture()
def logger():
import logging
log = logging.getLogger(__name__)
log.info("before the test")
return log
def test_log(logger):
logger.info("during the test")
raise Exception
```
</details>
<details>
<summary>Before</summary>
</details>
<details>
<summary>After</summary>
</details>
> Append a line break after captured log sections

- README.rst
- testing/test_pytest_html.py
Seems like ´optionalhook´ was never used.
´hookwrapper´ generated `PytestUnknownMarkWarning`
and I couldn't find anything regarding it explicitly in the changelog of `pytest`.
Replaced it with `@pytest.hookimpl(hookwrapper=True)` which did not generate any warnings.
Care to shed some light on the above @nicoddemus @RonnyPfannschmidt ?
> Remove unused and undocumented markers

- pytest_html/plugin.py
- testing/test_pytest_html.py
- tox.ini
Instead of a combination of human readable filename and hash, let's try a filename with cross-OS friendly formatting.
Fixes #214
Fixes #213
> Fix assets file naming to work across both *nix and windows

- pytest_html/plugin.py
- testing/test_pytest_html.py
When using custom CSS file I'm getting following warning:
```
/home/nelchael/.local/share/virtualenvs/functional-tests-IjeTcJ7i/lib/python3.7/site-packages/pytest_html/plugin.py:71: ResourceWarning: unclosed file <_io.TextIOWrapper name='resources/pytest-html-custom.css' mode='r' encoding='UTF-8'>
open(csspath)
ResourceWarning: Enable tracemalloc to get the object allocation traceback
```
This fixes it by closing the opened file. If I'm understanding it correctly, the file is opened just to make sure it exists here, so it could be potentially replaced with `os.access` call, but it's entirely optional.
> Close opened resource.

- pytest_html/resources/main.js
Currently it only sets the toggles for initial sort columns without actually doing the sorting.
This fixes https://github.com/pytest-dev/pytest-html/issues/247
> Trigger sorting for initial sort column

- pytest_html/plugin.py
- testing/test_pytest_html.py
Support utf8 display
[before]：
TestForSyncProduct::test_1_valueValid[test Case Name-add]  
TestForSyncProduct::test_2_valueValid[\u6d4b\u8bd5\u7528\u4f8b\u540d\u79f0-update]
[now]：
TestForSyncProduct::test_1_valueValid[test Case Name-add]
TestForSyncProduct::test_2_valueValid[测试用例名称-update]
> Support utf8 display

- pytest_html/resources/style.css
PRevious min-width caused undesired horizontal scrolls even on a 5K
display with 1/2 split screen. Reduced value allows users to better
use their screens.
> Fix min-width which produced horizontal scrolls

- pytest_html/extras.py
- pytest_html/plugin.py
- pytest_html/resources/style.css
- testing/test_pytest_html.py
This feature enables the use of extra videos in the reports in the same way as images are used.
```
extra.video(content, name="Video", mime_type="video/mp4", extension="mp4")
extra.mp4(content, name="Video")
```
- Videos may be included as reference, or as standalone
- Both of these cases are managed as the images are. Base64 encoding is used to pack the video as standalone data if needed.
- Extra video and windows path for videos are both added to the unit tests.
- Video and images were refactored to use a common media function internally to eliminate code duplication.
> Video support for mp4 format

- pytest_html/plugin.py
- testing/test_pytest_html.py
This pull request fixes #245 by sorting environment metadata dictionaries by keys.
- This fix does not implement any form of recursion. This means that if you have a metadata value which has a dictionnary value, this inner dictionary will not be sorted.
- In order to be able to compare the dictionary key values, they are cast as string. This allows a lexical sorting order, which is a natural way of sorting.
> Added support for ordering metadata dictionaries by key.

- README.rst
- pytest_html/plugin.py
- testing/test_pytest_html.py
> Control render using configuration

- pytest_html/plugin.py
- pytest_html/resources/main.js
- testing/test_pytest_html.py
Fixes #239 (again)
Had placed the `collapsed` class in the wrong tag.
Which in the end was a good thing since I discovered that JS needed an update as well to display the correct CSS (show/hide text).
> Fix collapsable bug

- README.rst
- pytest_html/hooks.py
- pytest_html/plugin.py
- testing/test_pytest_html.py
I think it is a good thing to be able to have a customizable report title that is not always the same as the file name.
As it is my first merge request on this project I'm open to any comment.
> Add hook to change report main title

- README.rst
- pytest_html/plugin.py
- testing/test_pytest_html.py
Adds a fixture, `extra`, which can be used to add extra content directly in a test function without having to implement hooks.
> Add extra fixture

- pytest_html/plugin.py
- testing/test_pytest_html.py
> Remove usage of funcargs

- testing/test_pytest_html.py
- tox.ini
The [issue](https://github.com/pytest-dev/pytest/issues/6936) with TerminalWriter in `pytester` is causing tests to fail.
> Better fix for TerminalReporter issue

- pytest_html/plugin.py
- testing/test_pytest_html.py
When adding a Base64 encoded image to a non-self contained report, only an empty link is created but no image.
> Fix image missing when using Base64 content

- CHANGES.rst
- testing/test_pytest_html.py
See #265 and related pytest-dev/pytest-selenium#237.
In #260, one of the three paths through the new `_make_media_html_div` lost the ability to embed its inner content. This PR adds tests for that (first commit, they failed) and adds back the embedding (second commit).
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pytest-dev/pytest-html/298)
> Fix embedded images (and videos)

- tox.ini
It does enable pytest-html reporting on its own test runs, so we
can easily see the outcome of the testing. This will also allow
publishing the results on CI/CD pipelines.
Reports are generated in the same location as tox logs, so they
do not overlap.
> Use pytest-html when running its own tests

- development.rst
The link to `Tox` was pointing to what Firefox deemed a potential security risk. This PR updates the link to `Tox` to point to its readthedocs page
See https://github.com/pytest-dev/pytest-html/issues/300
> Update link to Tox

- CHANGES.rst
- pytest_html/plugin.py
- testing/test_pytest_html.py
> Rename "slave" -> "worker" for xdist compatibility

- pytest_html/plugin.py
- testing/test_pytest_html.py
- tox.ini
Some filesystems do not support filenames that are 255 characters long. Notably, [aufs](https://en.wikipedia.org/wiki/Aufs) used by CircleCI only supports filenames up to 242 characters.
By making this a configurable option, we allow users to set their desired length limit.
> Make the maximum asset filename length configurable.

- setup.py
Avoid incompatibility issues caused by https://github.com/pytest-dev/pytest/issues/7559
We only avoid 6.0.0 because a fix will be included in 6.0.1
> Avoid pytest 6.0.0

- CHANGES.rst
- pytest_html/plugin.py
- pytest_html/resources/main.js
- testing/js_test_report.html
- testing/test.js
As per the title, make the `Links` column of the `Results` table sortable
Closes https://github.com/pytest-dev/pytest-html/issues/242
> Make the links column in the results table sortable

- pytest_html/plugin.py
- testing/test_pytest_html.py
- tox.ini
> Strip ANSI escape sequences when ansi2html is missing

- .travis.yml
- tox.ini
Start testing pytest with code from pytest master and with prereleases of other dependencies, allowing us to detect breakages before upstream releases are made.
This change needs https://github.com/pytest-dev/pytest-html/pull/319 merged first in order to get CI/CD green.
> Enable devel testing job

- .travis.yml
- pytest_html/plugin.py
- testing/test_pytest_html.py
- tox.ini
Simplifies testing matrix by mocking the absence of ansi2html support.
Fixes: #327
> Consolidate tox environments

- .pre-commit-config.yaml
- README.rst
- pytest_html/__init__.py
- pytest_html/plugin.py
- testing/test_pytest_html.py
Sync the ` .pre-commit-config.yaml` file with `pytest`'s as much as possible for a better developer experience.
The following diffs that cause `pre-commit` behavior differences between the two `pre-commit` workflows still exist:
```
gnikonorov:~/pytest-html$ diff .pre-commit-config.yaml ../pytest/.pre-commit-config.yaml
...
>           - flake8-docstrings==1.5.0
...
> -   repo: https://github.com/asottile/setup-cfg-fmt
>      ...
> -   repo: https://github.com/pre-commit/mirrors-mypy
...
46a61,82
>     -   id: changelogs-rst
>          ....
>     -   id: py-deprecated
>         ...
gnikonorov:~/pytest-html$
```
This is why:
- `flake8-docstrings`: requires a big documentation push, so I deferred
- `setup-cfg-fmt`: requires changes to `setup.cfg` which I believe should tackled separately
- …
> Sync .pre-commit-config.yaml with pytest

- CHANGES.rst
- pytest_html/plugin.py
- testing/test_pytest_html.py
I believe this would resolve #131 ... however it isn't really optimal, I didn't want to dig into the html logic, so instead just moved it to be post processed and tried to coerce the test result into what the existing code seemed to want.
> Post process html to include teardown in log

- .github/workflows/tox.yml
- tox.ini
This addressed silent regression that was caused by pytest 6.1.x removal of private member which was used by rerunfailures plugin. This broke our `tox -e devel` job and because we did not run it on CI, it took 3 months discover the issue.
- runs devel testing on CI
- install ansi2html and pytest-rerunfailures from git in devel job
- temporary disable pytest install from git due to known bug. I will personally revert this part as soon the issue is fixed upstream.
Related: https://github.com/pytest-dev/pytest-rerunfailures/issues/134
> Enable devel pipeline

- .github/workflows/tox.yml
Fixes issue that caused duplicated jobs running for all PRs coming from internal temporary branches. Duplicated jobs are confusing and also cause performance degradation.
A thumb rule is that branches pattern configured for the workflow should match the branch protection pattern from repository settings.
> Avoid duplicate builds on github

- pytest_html/extras.py
- pytest_html/plugin.py
Stop shadowing the `format` builtin function, since this is bad practice.
> Stop shadowing the 'format' builtin

- .github/workflows/tox.yml
- setup.cfg
- setup.py
- tox.ini
- enable tox py39 env
- expose py39 support in project metadata
- enable py39 github workflow
- corrects mistake on universal wheel (no py2 support)
> Add support for py39

- .pre-commit-config.yaml
Add [flake8-builtins](https://pypi.org/project/flake8-builtins/) to our workflow so that we prevent committers from accidentally shadowing builtins.
With this plugin, changes like this:
```
diff --git a/pytest_html/plugin.py b/pytest_html/plugin.py
index c35e0b1..ded4553 100644
--- a/pytest_html/plugin.py
+++ b/pytest_html/plugin.py
@@ -693,6 +693,7 @@ class HTMLReport:
self.append_failed(report)
def pytest_sessionstart(self, session):
+        format = "this is shadowing a builtin"
self.suite_start_time = time.time()
def pytest_sessionfinish(self, session):
```
Would trigger an error like `A001`:
```
flake8...................................................................Failed
- hook id: flake8
- exit code: 1
pytest_html/plugin.py:696:9: A001 variable "format" is shadowing a python …
```
> Add flake8-builtins plugin to the flake8 precommit hook

- pyproject.toml
- tox.ini
Support [isolated builds](https://tox.readthedocs.io/en/latest/config.html#conf-isolated_build) in `tox`, for a better developer experience
> Support tox isolated builds

- pytest_html/plugin.py
Replace os.path.exists checks with os.makedirs(exist_ok=True) which helps with race conditions when running tests with pytest-parallel or pytest-xdist.
> Use os.makedirs(exist_ok=True).

- CHANGES.rst
- pytest_html/plugin.py
- testing/test_pytest_html.py
Make `pytest-html` respect the `--capture=no` and `-s` pytest flags as requested in https://github.com/pytest-dev/pytest-html/issues/171.
Note that this only partially resolves the issue. We should also respect `--show-capture=no`, but I will add that in a follow up pr to make the changes smaller.
> Respect pytest --capture=no and -s flags

- CHANGES.rst
Prep version 3.0.0 for release as discussed in https://github.com/pytest-dev/pytest-html/issues/355. Major bump is due to https://github.com/pytest-dev/pytest-html/pull/347
I plan on releasing a new version the same day this PR merges
> Prep version 3.0.0 for release

- CHANGES.rst
- pytest_html/plugin.py
- testing/test_pytest_html.py
Make `pytest-html` respect the `--show-capture=no` pytest flag. Closes https://github.com/pytest-dev/pytest-html/issues/171
> Respect --show-capture=no flag

- pyproject.toml
- setup.py
This fixes the issue of releasing test.pypi.org containers that were not tagged by making the versioning compatible with publishing requirements (taken from other places where I am using it, mainly avoids using ``+`` in version and instead produces something like ``2.1.2.dev47`` which is accepted.
Related: https://github.com/pytest-dev/pytest-html/issues/322#issuecomment-721315174
> Assure scm versioning is pypa compatible

- development.rst
This removes the step in the release notes on updating the `package.json` file, which is outdated. [The file](https://github.com/pytest-dev/pytest-html/blob/master/package.json) does not have a `version` field anymore, so this is confusing.
I'm also rewriting the release instruction list as an RST [ordered list](https://sublime-and-sphinx-guide.readthedocs.io/en/latest/lists.html#ordered-lists), as it'll be easier to maintain than using numbers. If we use numbers and don't number the list correctly it won't format correctly whereas using the pound sign is always guaranteed to format properly.
> Remove outdated release instruction

- README.rst
Add a coverage badge to the `README.rst` file now that we have codecov up. The link was recommended by codecov in the Settings -> Badge  section under 'RST'
> Add codecov badge to readme

- CHANGES.rst
- src/pytest_html/plugin.py
- testing/test_pytest_html.py
Stop attaching the rerun entries created by [pytest-rerunfailures](https://github.com/pytest-dev/pytest-rerunfailures) to  reports.
When we introduced our post processing step we incorrectly lumped in rerunfailures reruns ( see https://github.com/pytest-dev/pytest-html/pull/271 ), which caused this issue. To fix it, we now treat each rerun as its own test which is what the original behavior was. I confirmed that behavior is the same as v2.1.1 now.
I'd also like to make a release after this merges, since this is a bugfix for the `v3.0.0` release if no one objects
Closes https://github.com/pytest-dev/pytest-html/issues/374
> Stop attaching test reruns to final test report entries

- README.rst
Fix a few typos in the readme and remove unneeded imports from code examples in the readme.
> Fix readme typos

- CHANGES.rst
Set the proper date for `v. 3.1.0` due to tomorrow's release. The date picked is the date the release will be published to PyPI.
> Prep version 3.1.0 for release 

- README.rst
- docs/user_guide.rst
As per the title, explain how to modify the environment section in a report after tests are finished.
Change made as per https://github.com/pytest-dev/pytest-html/issues/373#issuecomment-739431537
Closes https://github.com/pytest-dev/pytest-html/issues/373
**NOTE**: This needs to be moved if https://github.com/pytest-dev/pytest-html/pull/402 merged before this PR is in
> Document how to modify the environment section after tests are finished 

- src/layout/css/style.scss
- src/pytest_html/resources/style.css
* used scss variables for reoccur values
* used scss math to calculate values that depend on variables.
also:  scss allowes nesting of css selectors, which was applied here
the CSS was compiled based on changed SCSS.
changes in this PR are related to #383
> Use scss nesting & variables

- .eslintrc.json
- src/pytest_html/plugin.py
- src/pytest_html/resources/main.js
- testing/test.js
This PR enables [camelcase](https://eslint.org/docs/rules/camelcase) in eslint. I think this makes sense as most of the JavaScript in this repo is already camelcased, and it makes sense to have all variables follow the same convention.
I tested the changes locally and couldn't find any issues with this PR.
> Enable eslint camelcase rule

- CHANGES.rst
- src/pytest_html/plugin.py
- testing/test_pytest_html.py
Make the report tab title the same as the report name in the body for consistency.
Closes https://github.com/pytest-dev/pytest-html/issues/412
> Make the report tab title reflect the report name

- tox.ini
Issue with pytest latest should be resolved now.
> Re-enable tests against latest pytest

- Pipfile
- testing/test_pytest_html.py
Blocked by #416 
I'm thinking about opening a PR with pytest-rerunfailures so that we can provide a condition for the rerun. I only want it to rerun on windows machines.
The styling/indentation changes to .pre-commit-config.yml was made by my yaml linter.
I'm reluctant to set #395 to "fixed" by this PR.
> Handle flaky windows test by rerunning

- docs/api_reference.rst
- docs/conf.py
- docs/index.rst
This PR adds information on the plugin hooks to our read the docs documentation.
> Add plugin hooks to RTD documentation

- package.json
Stop classifying dev dependencies as non dev dependencies in the `package.json` file
> properly classify all npm dependencies

- .pre-commit-config.yaml
- README.rst
- docs/changelog.rst
- docs/development.rst
- docs/index.rst
Move the changelog to read the docs, since it would be a better user experience to have it with the rest of the documentation.
> Move the changelog to read the docs

- docs/changelog.rst
- docs/user_guide.rst
- src/pytest_html/resources/main.js
Implement a new query parameter, `visible`, to control visibility of test results on page load.
Note that `QUnit` makes testing this cumbersome. I tested this locally with all possible combinations and things worked as expected ( as did not passing this argument ). I opened https://github.com/pytest-dev/pytest-html/issues/432 to migrate off QUnit and noted the need for URL parameter tests in the issue.
Closes https://github.com/pytest-dev/pytest-html/issues/399
> Implement the visible URL query parameter to control visibility of test results on page load.

- docs/changelog.rst
- docs/user_guide.rst
- src/pytest_html/html_report.py
- src/pytest_html/plugin.py
- testing/test_pytest_html.py
This PR enables the redaction of environment table values based on the newly added `environment_table_redact_list` INI key.
Please see the following for an example of a redacted environment table entry (`MY_SECRET_KEY`):
Closes https://github.com/pytest-dev/pytest-html/issues/233
> Allow for redacting of environment table values

- .github/workflows/actions.yml
Disable Codecov until someone has time to upgrade to v2 and figure out why it fails (after upgrading).
Also disable pypy3, because: https://github.com/actions/setup-python/issues/311
> Disable Codecov

- .github/workflows/tests.yml
GitHub Actions recently introduced [reusable workflows](https://github.blog/2021-11-29-github-actions-reusable-workflows-is-generally-available/).
I want to use that functionality to split out the different workflows to make them a little bit more focused and easier to understand.
This is a prepatory step to enable that.
> Add reusable workflow

- .github/workflows/tests.yml
Significant decrease as can been seen [here](https://github.com/pytest-dev/pytest-html/actions/runs/1750855366)
Down from almost 40 minutes to less than 10. The outlier now is Windows.
> Skip coverage for pypy3

- src/pytest_html/html_report.py
- src/pytest_html/plugin.py
- src/pytest_html/result.py
This PR changes all file and directory path handling to use `pathlib.Path` instead of using strings and `os.path` functions. The initial reason for this is that simply prepending `"file://"` to the path of the report does not generate a valid URI on Windows, where the directory separator is `\`, because you end up with something like `file://D:\proj\report.html`, which uses backslashes, and file URIs are [supposed to use forward slashes](https://en.wikipedia.org/wiki/File_URI_scheme#:~:text=Forward%20slashes%20should%20be%20used%20to%20delimit%20paths.). Instead we can use the [`pathlib.Path.as_uri()`](https://docs.python.org/3/library/pathlib.html#pathlib.PurePath.as_uri) function to get a valid URI. While I was at it, I changed the rest of the file[s] to use `pathlib.Path` as well.
> Use pathlib.Path for file path handling

- setup.py
This dependency was implicitely set through pytest. With [1] the dependency was removed from pytest, so pytest-html fails with:
ModuleNotFoundError: No module named 'py.xml'; 'py' is not a package
Specify it explicitely as dependency to fix the issue.
[1] https://github.com/pytest-dev/pytest/commit/19dda7c9bdc8ef71c792e0f77a9595bfad8d9248
Signed-off-by: Erik Bloß <erik.bloss@smartmicro.de>
> Add py as dependency

- pyproject.toml
- setup.py
pyproject.toml:
Switch to setuptools-scm >= 7.0.0, which allows dropping setuptools-scm-git-archive.
Remove wheel, as it is not required for building using PEP517 tooling (i.e. setuptools, setuptools-scm, build, installer).
setup.py:
Raise required setuptools-scm version to match the build-system requirements in pyproject.toml.
> Switch to setuptools-scm >= 7.0.0

- src/pytest_html/nextgen.py
- src/pytest_html/resources/index.jinja2
- src/pytest_html/scripts/datamanager.js
- src/pytest_html/scripts/dom.js
- src/pytest_html/scripts/filter.js
- src/pytest_html/scripts/main.js
- src/pytest_html/scripts/storage.js
- testing/unittest.js
Previously we were overwriting some of the attributes coming out of pytest (like `nodeid`) and since this data is shared with other plugins, that's a bad idea.
This PR aims to fix that.
> refactor: stop overwriting pytest data

- .github/workflows/actions.yml
- .github/workflows/tests.yml
- docs/user_guide.rst
- src/pytest_html/nextgen.py
- src/pytest_html/plugin.py
- testing/test_unit.py
- tox.ini
Remove the duration_formatter and warn if it's used as it's no longer functional in 4.x.
> update: duration_format renders deprecation warning

- src/pytest_html/nextgen.py
Apparently there's an expectation that the report has the config object attached?
> fix: Add config to report object

- testing/test_integration.py
The original issue (detailed [here](https://github.com/pytest-dev/pytest-html/pull/591#issue-1619086434)) was fixed by: https://github.com/pytest-dev/pytest-html/pull/597
This PR just adds the test.
> fix: Report fails to render with pytest-xdist

- docs/user_guide.rst
- src/pytest_html/nextgen.py
- src/pytest_html/scripts/dom.js
- src/pytest_html/scripts/storage.js
- testing/test_integration.py
This PR fixes two things.
- We broke backwards compat where you could do `del cells[:]` to remove an item from the report. This is an interim solution for that.
- We also broke backwards compat where you could insert cells and have them sortable.
> Fix: Table row hook

- .github/workflows/tests.yml
- .gitignore
- .nycrc
- package-lock.json
- package.json
Add test coverage for javascript and upload to codecov.io
> chore: Add code coverage for JS

- src/pytest_html/nextgen.py
- src/pytest_html/scripts/datamanager.js
- src/pytest_html/scripts/dom.js
- src/pytest_html/scripts/main.js
- testing/test_integration.py
The logging output/capture was broken in the legacy report, where "teardown" logs wasn't visible in the tests log output.
> fix: Missing logging in report

- src/pytest_html/basereport.py
- src/pytest_html/scripts/dom.js
- src/pytest_html/table.py
This is an extremely ugly hack.
But I feel we need it short term for backwards compatibility.
The idea is to later replace this with something that is more robust and doesn't depend on primitives/low-level APIs.
> fix: Replacing log HTML

- src/pytest_html/scripts/dom.js
- src/pytest_html/scripts/utils.js
- src/pytest_html/table.py
- testing/test_integration.py
- testing/unittest.js
Since `cells` was of type `list` in the legacy report, people might also use `appends` (apart from list assignment and `insert`) so for backwards compat, we'll add support for now.
This will be deprecated once we've decided on what the "Table" API should look like.
> Fix: Handle appends on table hooks

- src/pytest_html/scripts/dom.js
- testing/test_integration.py
In the legacy report any log lines starting with `E` was colored red, which aided readability.
This was lost in the rewrite, so let's re-add it.
> Fix: Color E(xecption) lines in the log red

- pyproject.toml
- src/pytest_html/resources/index.jinja2
- src/pytest_html/scripts/main.js
- testing/test_integration.py
Making the order of the outcomes in the summary the same as `pytest` has in the terminal.
> Fix: Order and layout of outcome summary

- src/layout/css/style.scss
- src/pytest_html/resources/index.jinja2
- src/pytest_html/resources/style.css
- src/pytest_html/scripts/main.js
Should `style.css` be gitignored since it's generated by `style.scss`?
Also, I'd like the `hide|show details` to be styled differently. How can I accomplish that?
More generally, is this the correct way of solving this? Including changes made to the template.
Fixes: #622
> Feature: Add hide-able Environment Table

- .github/workflows/tests.yml
- src/pytest_html/basereport.py
- src/pytest_html/hooks.py
- testing/test_integration.py
- testing/test_unit.py
> Feature: Add 'session' to results summary hook

- src/pytest_html/basereport.py
- src/pytest_html/report_data.py
- src/pytest_html/table.py
Not a 100% 1-to-1 with the Legacy report, but good enough.
In Legacy the `data` argument also contained any HTML added via `extras.HTML`, but since that is also under user control with even more granular control - any modifications previously done using the hook, can be done directly to the extras object instead. 
Closes: #667
> Fix: results table html hook

- src/pytest_html/basereport.py
- src/pytest_html/report_data.py
- testing/test_integration.py
There seems to be multiple issues with `pytest-rerunfailures` and/or `pytest` related to captured logs.
More info here: https://github.com/pytest-dev/pytest-rerunfailures/pull/124
Until they have been fixed or I've figured out exactly what the problem is, we won't attach logs to "reruns".
Not that there's still an issue where "teardown" logs are added multiple times in the output from `pytest`. Which in turn means that's what ends up in the report.
> Fix: Logging issues with teardown

- src/pytest_html/plugin.py
- src/pytest_html/report_data.py
- src/pytest_html/scripts/dom.js
- src/pytest_html/scripts/sort.js
- src/pytest_html/scripts/storage.js
Add ini-configuration option to set the initial sorting column.
> Feature: Add initial sort column as ini

- docs/user_guide.rst
- src/pytest_html/scripts/datamanager.js
- src/pytest_html/scripts/dom.js
- src/pytest_html/scripts/filter.js
- src/pytest_html/scripts/index.js
- src/pytest_html/scripts/main.js
- src/pytest_html/scripts/mediaviewer.js
- src/pytest_html/scripts/sort.js
- src/pytest_html/scripts/storage.js
The Environment table had a bug where it wouldn't toggle (show/hide) when any other toggle was activated.
> Fix: Environment table toggle bug

- .github/workflows/tests.yml
- tox.ini
This PR: https://github.com/tox-dev/tox/pull/3089 broke the tests.
Not sure if we we're getting away with, or if their PR introduced a bug. Don't have time to find out.
> Chore: Fix tox

- docs/changelog.rst
- src/pytest_html/basereport.py
- testing/test_integration.py
- testing/test_unit.py
> Fix: Use absolute path for the report

- docs/changelog.rst
- src/pytest_html/resources/index.jinja2
> Pytest html fix reload button typo

- src/pytest_html/basereport.py
- src/pytest_html/report_data.py
> fix: Broken duration

- docs/user_guide.rst
- src/pytest_html/basereport.py
- src/pytest_html/plugin.py
- src/pytest_html/util.py
Two changes in this PR:
- Make generating the HTLM report after each test optional, reverting to the behaviour of v3 and earlier versions.
- Remove the `cleanup_unserializable` function in effort to improve performance. If this brings any issues, we can make a more conscious effort of handling those errors.
Fixes: #751 
Fixes: #742 
Fixes: #741
> fix: Revert report generation to full run

- src/pytest_html/basereport.py
- src/pytest_html/report_data.py
- testing/test_integration.py
> fix: Add collections errors to report

- docs/user_guide.rst
The example results table modification shown in the docs is broken since https://github.com/pytest-dev/pytest-html/pull/599, some hardcoded strings are used instead of the dynamically generated report entry data.
> Fix results table modification documentation

- scripts/npm.py
> fix: Only run npm when building from source

- src/pytest_html/basereport.py
- src/pytest_html/report_data.py
- testing/test_integration.py
> fix: Escaping HTML in log

- src/pytest_html/basereport.py
- testing/test_integration.py
It's not pretty, but at least it fixes the problem.
Fixes: #777
> fix: Extras from setup/teardown missing in report

- src/pytest_html/basereport.py
> fix: Total duration when running in parallel

- pyproject.toml
Project is licensed as MPL-2.0 but a MIT license classifier is being used, resulting in the wrong license being displayed on PyPI. Changing classifier to the correct one for the actual project license.
> Fix license classifier in pyproject.toml

- src/pytest_html/scripts/dom.js
- testing/test_integration.py
If you move 'col-result' to right hand side in results-table, it always shows 'hide details' even details are already collapsed.
the reason is, col-result is not the first td element of the results-table anymore and therefore it adds collapsible class to first td element.
because of this reason, below function does not work:
```
.col-result:hover::after {
content: " (hide details)";
}
.col-result.collapsed:hover::after {
content: " (show details)";
}
```
changing '.collapsible > td' to '.collapsible > col-result' fix this problem.
> Fix for #806 (if results table order changed, hide/show details hover over broken)

- .pre-commit-config.yaml
- pyproject.toml
Will prevent most issues when doing parallel modifications of the pyproject.toml conf. (Every changes in pyproject.toml is automated).
> [pre-commit] Add pyproject-fmt to normalize the pyproject.toml

- .pre-commit-config.yaml
- pyproject.toml
- src/pytest_html/resources/index.jinja2
My colleague had issues with displaying generated reports:
The report was correctly displayed on:
- my Linux/Firefox machine.
- his Windows/Edge
The report had no content or even showed blank page on:
- on his computer windows/firefox
- on his computer windows/chrome
When I checked the generated report file I noticed that:
- some tags were not properly closed
- some special characters are not escaped properly
Examples
- https://github.com/pytest-dev/pytest-html/blob/4b714aa558b1f7b8af1035033e4e94601ef75c4b/src/pytest_html/resources/index.jinja2#L32
- https://github.com/pytest-dev/pytest-html/blob/4b714aa558b1f7b8af1035033e4e94601ef75c4b/src/pytest_html/resources/index.jinja2#L51
This PR also adds `djlint` to pre-commit hook.
- Fixed tags in report template.
- Added pre-commit hook to …
> Fix report template
