pytest_html/resources/main.js
pytest_html/resources/style.css

Expand / Collapse for extras-row

---

pytest_html/plugin.py
pytest_html/resources/main.js

Order table without JS

---

pytest_html/plugin.py
pytest_html/resources/main.js
test_pytest_html.py

No checkboxes when JS is disabled

---

pytest_html/resources/main.js

Title of checkbox disappears when unchecked

---

pytest_html/__init__.py
pytest_html/plugin.py

Created two constants in the __init__ file to hold the VERSION and
PYPI_URL.
This patch fixes issue #86.

Added version number and pypi url to report header

---

README.rst

Added example of using `name` param

Doc addition

---

README.rst

Add a contributing section to the README

---

pytest_html/plugin.py
testing/test_pytest_html.py

Report collection errors in HTML report

---

README.rst
pytest_html/plugin.py
testing/test_pytest_html.py

Support custom CSS files for changing report appearance

---

README.rst
pytest_html/plugin.py
testing/test_pytest_html.py

Disable sort on environment table when metadata is ordered

---

README.rst

Add a nice conda-forge badge to the README

Add conda-forge badge to README

---

pytest_html/plugin.py

Stop filtering out falsy environment values

---

.pre-commit-config.yaml
.travis.yml
Pipfile
README.rst
developtment.rst
tox.ini

Let's use `pre-commit` for this project too.

Use pre-commit to streamline development

---

CHANGES.rst
pytest_html/plugin.py
pytest_html/resources/main.js
testing/test_pytest_html.py

Release v1.22.1

---

.travis.yml
setup.py
tox.ini

- Advertise support for py38
- Adds CI/CD jobs for testing py38

Enable py38 testing

---

.github/workflows/actions.yml
testing/test_pytest_html.py

Hopefully the last try for this. @gnikonorov sorry about the roundabouts.

Enable testing on Windows and MacOS

---

.coveragerc
codecov.yml

Disable codecov PR comments as requested [here](https://github.com/pytest-dev/pytest-html/pull/380#issuecomment-734155689)
The change was made as per [the codecov docs](https://docs.codecov.io/docs/pull-request-comments#disable-comment)

Disable codecov PR comments

---

src/layout/css/style.scss
src/pytest_html/resources/style.css

fixed css sort tringles

---

CHANGES.rst

Set release date for v3.1.1 to 12/13, which is when I will release to PyPI

Set release date for v3.1.1

---

package.json

Removes the phantomjs dependency as per https://github.com/pytest-dev/pytest-html/issues/418
Closes https://github.com/pytest-dev/pytest-html/issues/418

remove phantomjs dependency

---

.github/workflows/actions.yml
.github/workflows/tests.yml

First PR to use the reusable tests workflow.
Next will create a separate Nightly (scheduled) workflow.

Use the tests reusable workflow

---

.github/workflows/actions.yml
.github/workflows/release-drafter.yml
README.rst
docs/development.rst
docs/index.rst
tox.ini

Reverts pytest-dev/pytest-html#560

Revert "Rename master branch to main"

---

src/pytest_html/basereport.py

Backwards compatibility wrt `py.xml` html.
Issue deprecation warning and cast to string.

Fix: Handle legacy py html

---

docs/changelog.rst
src/pytest_html/report_data.py
testing/test_integration.py

fix: Incorrect label for xfailed

---

testing/test_integration.py

test: Add UTF8 test

---

docs/changelog.rst
src/pytest_html/scripts/main.js
testing/test_integration.py

fix: original sort order

---

.pre-commit-config.yaml
src/pytest_html/basereport.py
src/pytest_html/extras.py
testing/legacy_test_pytest_html.py

Upgrade tool for python 3.9
